// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhRWmOOClfmVHfHUhMNt-crx7GpbDz6o',
    appId: '1:419213221554:web:a272c77c5775c9db1eb3ab',
    messagingSenderId: '419213221554',
    projectId: 'flutter-projects-89ffd',
    authDomain: 'flutter-projects-89ffd.firebaseapp.com',
    storageBucket: 'flutter-projects-89ffd.firebasestorage.app',
    measurementId: 'G-S4BEH4D9XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSyHDAKIl84OH7nGfi8RfdtILO6qCq33A',
    appId: '1:419213221554:android:ef1ecf0e2d3d6da31eb3ab',
    messagingSenderId: '419213221554',
    projectId: 'flutter-projects-89ffd',
    storageBucket: 'flutter-projects-89ffd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAg4MjhlhKwQCp3ooagiPRdHCOBk86Zr0',
    appId: '1:419213221554:ios:a4fbb33c4faf99de1eb3ab',
    messagingSenderId: '419213221554',
    projectId: 'flutter-projects-89ffd',
    storageBucket: 'flutter-projects-89ffd.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAg4MjhlhKwQCp3ooagiPRdHCOBk86Zr0',
    appId: '1:419213221554:ios:a4fbb33c4faf99de1eb3ab',
    messagingSenderId: '419213221554',
    projectId: 'flutter-projects-89ffd',
    storageBucket: 'flutter-projects-89ffd.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyhRWmOOClfmVHfHUhMNt-crx7GpbDz6o',
    appId: '1:419213221554:web:3051ebbddc5677981eb3ab',
    messagingSenderId: '419213221554',
    projectId: 'flutter-projects-89ffd',
    authDomain: 'flutter-projects-89ffd.firebaseapp.com',
    storageBucket: 'flutter-projects-89ffd.firebasestorage.app',
    measurementId: 'G-PRKFG1GV0P',
  );
}
